# Generated by Django 5.1.7 on 2025-05-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_viajes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viaje',
            name='hora',
            field=models.TimeField(default='00:00'),
        ),
    ]
